--- !ditz.rubyforge.org,2008-03-06/project 
name: igorunit
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: igorunit
- !ditz.rubyforge.org,2008-03-06/component 
  name: python-scripts
- !ditz.rubyforge.org,2008-03-06/component 
  name: igor-code
releases: []

